### PR TITLE
CloudStack: fix in parsing of an empty body

### PR DESCRIPTION
**Pull request by konstan**
Fix for the issue when `AttributeError: 'str' object has no attribute 'values'` gets thrown in case of an empty body is retuned by the provider.

```
Traceback (most recent call last):
...
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/cloudstack.py", line 1089, in list_sizes
    method='GET')
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 188, in _sync_request
    headers=headers, method=method)
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 152, in _sync_request
    data=data, headers=headers, method=method)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 736, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 117, in __init__
    raise Exception(self.parse_error())
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 39, in parse_error
    values = list(body.values())[0]
AttributeError: 'str' object has no attribute 'values'
```

Exception after the change:

```
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 188, in _sync_request
    headers=headers, method=method)
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 152, in _sync_request
    data=data, headers=headers, method=method)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 736, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 117, in __init__
    raise Exception(self.parse_error())
  File "/usr/lib/python2.6/site-packages/libcloud/common/cloudstack.py", line 48, in parse_error
    raise error
libcloud.common.types.ProviderError: 'WARNING: error message text sent by provider was empty.'
```

### CODE REVIEW

**Comment by Kami** [comment]
Thanks, the change looks good, but can you please also add a test case for it?

**Comment by Kami** [comment]
@konstan bump^^

**Comment by Kami** [comment]
I'm working on a 0.18.0 release so I merged patch into trunk.

Please make sure to submit a new PR with the corresponding tests when you have a chance.

Thanks.

**Comment by konstan** [comment]
Oops... Sorry for not replying promptly (vacations time).  Yes, sure - next time with a test!  Thanks for the merge.
