### ISSUE TITLE
AuroraDNS: bug in exception handling

### ISSUE THREAD

**Issue by macfreek** [apache/libcloud#1521]
## Summary

When trying to use the DNS driver auroradns with incorrect credentials, a bug is triggered in `AuroraDNSResponse.parse_error()`. It passes the wrong attributes, and leads to an unintended TypeError.

### Code to reproduce:

```
#!/usr/bin/env python3

from libcloud.dns.types import Provider
from libcloud.dns.providers import get_driver

api_key = '123456'
secret_key = 'this_is_the_wrong_password'

cls = get_driver(Provider.AURORADNS)
driver = cls(api_key, secret_key)

for zone in driver.iterate_zones():
    print(zone)
```

### Expected exception:

This should have raised an `ProviderError: Authorization failed`

### Actual exception:

`TypeError: __init__() got an unexpected keyword argument 'http_status'`

## Source of the bug:

This bug was introduced in commit de7862f, which includes the following rewrite:

```
-            raise ProviderError(value='Authorization failed', http_code=status,
-                                driver=self)
+            error['value'] = 'Authorization failed'
+            error['http_status'] = status
+            raise ProviderError(**error)
```

While the intention is clear, the author inadvertently changed the way `ProviderError` was called from `ProviderError(value=..., http_code=status)` to `ProviderError(value=..., http_status=status)`

This bug can easily be fixed by changing the line `error['http_status'] = status` to `error['http_code'] = status`

**Comment by Kami** [comment]
Resolved via #1522. Thanks again for the contribution.
